### ISSUE TITLE
Server refusing to connect

### ISSUE THREAD

**Issue by markopolojarvi** [linuxserver/docker-bookstack#58] opened 2020-03-07 08:14 UTC
I've tried to install this on two separate servers via docker-compose by copy/pasting services in the README, and in both it doesn't serve.

------------------------------

## Expected Behavior
Should serve Bookstack.

## Current Behavior
Doesn't serve Bookstack.

## Steps to Reproduce
1. Copy/paste docker-compose config from README with the addition of APP_URL
2. docker-compose up -d
3. Access it through a browser

## Environment
**OS:** Ubuntu 16.04
**CPU architecture:** x86_64      
**How docker service was installed:** Like docker's documentation shows

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
App Key found - setting variable for seds
Running config - db_user set
/var/run/s6/etc/cont-init.d/50-config: line 62: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 62: warning: command substitution: ignored null byte in input
Nothing to migrate.
```

**Comment by j0nnymoe** [comment] 2020-03-07 11:35
Post your exact docker-compose snippet for bookstack please

**Comment by markopolojarvi** [comment] 2020-03-07 11:43
```
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=REDACTED
      - DB_DATABASE=bookstackapp
      - APP_URL=https://not.real.com
    volumes:
      - bookstack_config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=REDACTED
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=REDACTED
    volumes:
      - bookstack_db:/config
    restart: unless-stopped
volumes:
  bookstack_db:
  bookstack_config:
```

**Comment by Pixtriks** [comment] 2020-03-12 13:11
I have the same issue but in my setup I have Bookstack behind Traefik.

**Comment by GeorgeHahn** [comment] 2020-03-15 05:14
I've found that startup can take a few minutes. After `nothing to migrate`, wait for:
```
...
Nothing to migrate.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by Pixtriks** [comment] 2020-03-15 07:47
Yeah I found that out as well but it doesn’t seem to be the cause of this issue. Even after waiting until those messages pop-up I still get a gateway timeout error.

**Comment by Ivan-Igorevich** [comment] 2020-03-19 04:01
same docker-compose file, blank white screen when I open service port, in container logs I have this output:
```
[cont-init.d] 50-config: executing... 
Generating BookStack app key for first run
App Key set to base64:L2p5lUBPCUjO3k2iq9manVYD+N7V3Y9p8FDTHiRdA0I= you can modify the file to update /config/BOOKSTACK_APP_KEY.txt
Running config - db_user set
/var/run/s6/etc/cont-init.d/50-config: line 67: warning: command substitution: ignored null byte in input

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.
[cont-init.d] 50-config: exited 0.
```

**Comment by Pixtriks** [comment] 2020-03-19 08:23
That is actually caused by the environment variables being incorrect on the Bookstack container. It should be DB_USERNAME and DB_PASSWORD. That should solve your problem. My issues seem to lie in the built in nginx configuration.

**Comment by Ivan-Igorevich** [comment] 2020-03-19 15:31
@Pixtriks thanks for your suggestion, can you, please guide me through the solution? here's my compose file 
<img width="413" alt="image" src="https://user-images.githubusercontent.com/12792352/77084141-9b40f280-6a0f-11ea-8f30-b25f6f409cff.png">

**Comment by Pixtriks** [comment] 2020-03-19 16:33
Of course! Under your Bookstack container change the environment variable of DB_USER to DB_USERNAME and DB_PASS to DB_PASSWORD.

Are you also running Bookstack behind Traefik? Because that is where my issue lies.

**Comment by ngvtien** [comment] 2020-03-25 01:02
Even with the recommended changes it still doesn't work
below is the error

 at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
   665|         // If an exception occurs when attempting to run a query, we'll format the error
   666|         // message to include the bindings with SQL, which will make this exception a
   667|         // lot more helpful to the developer instead of just the database's errors.
   668|         catch (Exception $e) {
 > 669|             throw new QueryException(
   670|                 $query, $this->prepareBindings($bindings), $e
   671|             );
   672|         }
   673|
 Exception trace:
 1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] Connection refused")
     /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
 2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")
     /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

**Comment by Nebucatnetzer** [comment] 2020-03-29 14:44
> Yeah I found that out as well but it doesn’t seem to be the cause of this issue. Even after waiting until those messages pop-up I still get a gateway timeout error. I think that for some reason Nginx built into this container isn’t playing nice with Traefik as a reverse proxy. Sadly I was unable to find anything of value in the logs..

I'm experiencing the same problem.
I reverted back to my Apache reverse proxy and it's running fine again.
The message that I got was `404 page not found`.
There wasn't anything useful in the error logs of Nginx.

**Comment by danhere** [comment] 2020-04-01 21:58
I didn't find switching DB_USER to DB_USERNAME and DB_PASS to DB_PASSWORD to work either. 

What did work for me was not setting a root password for the MySQL service. It obviously complains but it works now. Maybe the issue has something to do with that?

**Comment by Nebucatnetzer** [comment] 2020-04-13 20:48
> > Yeah I found that out as well but it doesn’t seem to be the cause of this issue. Even after waiting until those messages pop-up I still get a gateway timeout error. I think that for some reason Nginx built into this container isn’t playing nice with Traefik as a reverse proxy. Sadly I was unable to find anything of value in the logs..
> 
> I'm experiencing the same problem.
> I reverted back to my Apache reverse proxy and it's running fine again.
> The message that I got was `404 page not found`.
> There wasn't anything useful in the error logs of Nginx.
> 
> Edit:
> I'm going to compare Bookstack with the Heimdall (https://github.com/linuxserver/docker-heimdall) container.
> They should be reasonable similar.
> At least it looks like they have very similar Nginx configs.

The only solution that I was able to get working was an Nginx reverse proxy with Certbot installed on the Docker host.
Neither Traefik nor the LSIO Let's Encrypt containter were working for me.

**Comment by stumpylog** [comment] 2020-04-19 22:16
I'm also seeing issues with this container connecting.  I have no reverse proxy, it's accessed directly from an IP and port.  Nothing in the logs of either the container, nginx or php to indicate an issue.

Weirdly, I do see the favicon gets displayed.

**Comment by Wr0ngName** [comment] 2020-04-28 10:13
Same here, connection refused. Could not find the setting to adjust DB port. Default only???
One thing I am sure is my MariaDB cannot run on default port. Currently dropping the container for another one less invasive, if that works I know where the issue is.

**Comment by cazier** [comment] 2020-04-29 20:08
@Wr0ngName You can use a custom port for MariaDB by just appending that to the end of your DB_HOST variable like so: `DB_HOST=192.168.1.5:9201`

**Comment by bucky2076** [comment] 2020-05-07 06:34
I found multiple conflicts with the docker run command causing quite a bit confusion for me. Though I did get it working, but not in a supportable manner.
The DB_HOST parameter is used initially to update the .env file. Subsequent runs do not update the .env file, so have to do that manually.
The .env only supports the internal bridged ip address (e.g. 172.xxx.xxx). Unfortunatley these addresses are behind the docker dhcp/dns which can change frequently. It DID NOT work to put the container name in place of the IP.
Needs work imo.

**Comment by stumpylog** [comment] 2020-06-11 15:42
I solved my issue.  It was a problem with the database for me.  My database password was a passphrase with spaces.  That seems to cause issues in the .env file created.  Once I edited the necessary locations to remove the space, things started right up.

So try changing from "super secret password" to "supersecretpassword".

**Comment by Sepphod** [comment] 2020-07-05 07:14
I'am having the same issue like @Pixtriks. I am running bookstack behind a Traefik => BAD GATEWAY. If I am running it locally on the same machine but NOT behind the Traefik => everything runs smoothly. Is there any workaround?

**Comment by Sepphod** [comment] 2020-07-05 10:56
Ok I found my mistake => the port in the Traefik load balancer was wrong
correct is "traefik.http.services.bookstack.loadbalancer.server.port=80"

**Comment by edgeux** [comment] 2020-07-07 14:01
I found that the only way i could overcome the error was to edit the config/www/.env file and add the :

APP_URL=https://subdomain.yourdomain.co.uk

Having re-read the destructions, it mentions the APP_URL variable as an optional, but in this case its a requirement to get it working. 

yeah baby

**Comment by klutchell** [comment] 2020-08-18 14:03
Looking at the following line, I can see why `APP_URL` is not being applied in `www/.env`

https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L61

```bash
# set appurl if detected
[[ "${APP_URL}" ]] && sed -i "s,#\sAPP_URL.*,APP_URL=${APP_URL},g" /config/www/.env
```

This substitution is expecting `# APP_URL` but the example env file doesn't include a space: `#APP_URL`.

The workaround is to manually edit your `www/.env` file and avoid providing environment variables that would cause it to be overwritten.

**Comment by Nebucatnetzer** [comment] 2020-08-18 17:22
Great catch!
I can confirm that this is working and Traefik works now as well with Bookstack.

**Comment by Nebucatnetzer** [comment] 2020-08-21 07:38
@aptalca can you merge #62 please?

**Comment by BobWs** [comment] 2020-12-20 14:49
Having the same problem. The container keeps hanging on `nothing to migrate` Even after waiting for an half hour.
Changing The Tips from above didn't help.

**Comment by aptalca** [comment] 2020-12-20 15:17
It's not hanging. That's what it's supposed to say and move on

**Comment by BobWs** [comment] 2020-12-20 19:52
> It's not hanging. That's what it's supposed to say and move on

I know I have been using Bookstack for a while now and it has been working fine until now. I just moved over my container to Docker on a debian vm os and now it won’t start again.

**Comment by anarchist912** [comment] 2020-12-22 11:59
> I know I have been using Bookstack for a while now and it has been working fine until now. I just moved over my container to Docker on a debian vm os and now it won’t start again.

I waited 10 to 15 minutes until something happened after `nothing to migrate`. Then it worked.

**Comment by BobWs** [comment] 2020-12-23 07:27
> > I know I have been using Bookstack for a while now and it has been working fine until now. I just moved over my container to Docker on a debian vm os and now it won’t start again.
> 
> I waited 10 to 15 minutes until something happened after `nothing to migrate`. Then it worked.

I have waited 30 minutes still nothing happened. I reverted back to my  Synology Docker and It started instantly. The only difference between this and the docker on my debian vm is that Bookstack is linked to my mariadb via `—link mariadb:book-db` and that both are on the same docker network. And when I try Bookstack on my debian VM it fails, maybe because they are not on the same docker network?!

**Comment by snipes040** [comment] 2021-01-14 19:54
so I've been having the exact same issue behind traefik.  I can get it working if I specify the environment variables (ie. DB_USER, MYSQL_ROOT_PASSWORD) with a super weak plain text password in my docker-compose.yaml file such as Password123.  When I set it up using my environment variables that I've setup in /etc/environment with stronger/longer passwords it fails everytime with http 500 error.  I've also confirmed the environment variables are working by using: echo $APP_URL.  I've also confirmed there are no special characters or spaces in any of my passwords.  I should also mention I have 16 other containers running with environment variables set and they all work perfectly fine, hopefully this helps.

Here is my docker-compose file:

bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    restart: unless-stopped
    networks:
      - proxy
      - default
    depends_on:
      - bookstack_db
    ports:
      - 6875:80
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
      - APP_URL=${APP_URL}
    volumes:
      - /home/pi/docker/bookstack/config:/config
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:bookstack.${DOMAINNAME}
      - traefik.backend=bookstack
      - traefik.docker.network=proxy
      - traefik.port=80

  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    restart: unless-stopped
    networks:
      - default
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - bookstackapp:/config

Here is the error message in the logs as well:

 Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')
at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669

  665|         // If an exception occurs when attempting to run a query, we'll format the error
  666|         // message to include the bindings with SQL, which will make this exception a
  667|         // lot more helpful to the developer instead of just the database's errors.
  668|         catch (Exception $e) {
 > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|
  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by elamigosam** [comment] 2021-01-14 23:21
Hi,
I am getting this error:
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
App Key found - setting variable for seds
Running config - db_user set

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

I believe Mysql is not running, this is what I get in the linuxserver/mariadb container logs:

210114 15:18:10 mysqld_safe Logging to syslog.
210114 15:18:10 mysqld_safe Starting mysqld daemon with databases from /config/databases
210114 15:18:12 mysqld_safe Logging to syslog.
210114 15:18:12 mysqld_safe Starting mysqld daemon with databases from /config/databases
210114 15:18:14 mysqld_safe Logging to syslog.
210114 15:18:14 mysqld_safe Starting mysqld daemon with databases from /config/databases

This is what I get when I docker exec into the linuxserver/mariadb container and try to run mysqld:
root@b547283616d1:/# mysqld
2021-01-14 15:19:11 0 [Note] mysqld (mysqld 10.4.17-MariaDB-1:10.4.17+maria~bionic-log) starting as process 10580 ...
Cannot find checkpoint record at LSN (1,0x7fe6)
2021-01-14 15:19:11 0 [ERROR] mysqld: Aria recovery failed. Please run aria_chk -r on all Aria tables and delete all aria_log.######## files
2021-01-14 15:19:11 0 [ERROR] Plugin 'Aria' init function returned error.
2021-01-14 15:19:11 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
2021-01-14 15:19:11 0 [Note] InnoDB: Using Linux native AIO
2021-01-14 15:19:11 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2021-01-14 15:19:11 0 [Note] InnoDB: Uses event mutexes
2021-01-14 15:19:11 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-01-14 15:19:11 0 [Note] InnoDB: Number of pools: 1
2021-01-14 15:19:11 0 [Note] InnoDB: Using SSE2 crc32 instructions
2021-01-14 15:19:11 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2021-01-14 15:19:11 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2021-01-14 15:19:11 0 [Note] InnoDB: Completed initialization of buffer pool
2021-01-14 15:19:11 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2021-01-14 15:19:11 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2021-01-14 15:19:11 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2021-01-14 15:19:11 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-01-14 15:19:11 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-01-14 15:19:11 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-01-14 15:19:12 0 [Note] InnoDB: Waiting for purge to start
2021-01-14 15:19:12 0 [Note] InnoDB: 10.4.17 started; log sequence number 18336641; transaction id 3946
2021-01-14 15:19:12 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-01-14 15:19:12 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2021-01-14 15:19:12 0 [ERROR] Failed to initialize plugins.
2021-01-14 15:19:12 0 [ERROR] Aborting

Does any one have any ideas how to help mysql run, since it think its mysql that is not running, there for bookstack cant connect to mysql. or any ideas on how to rescue the data from the database? 
thanks

**Comment by snipes040** [comment] 2021-01-18 17:28
Hopefully this helps some people, as I was having major issues getting bookstack to get setup correctly.  It turns out, for some reason bookstack and mariadb were getting setup correctly (user, password, database, root user) HOWEVER it was for some reason not granting the user access to the databse.  I ran this command to give the user access manually, restarted the docker containers and it fired up right away.

**docker exec -it mariadb bash
GRANT ALL PRIVILEGES ON bookstack.* TO 'gilbn' IDENTIFIED BY 'mypassword';**

(https://technicalramblings.com/blog/how-to-install-bookstack-and-reverse-proxy-it-using-linuxserver-letsencrypt-on-unraid/)

Hopefully this helps some people out that have had the same issue as me with access denied errors when bringing up the containers.

**Comment by ajnasaboobacker** [comment] 2021-02-04 05:46
Setting up APP_URL variable fixed my issue.

Here is my stack.

---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1001
      - PGID=1001
      - DB_HOST=172.22.0.2
      - DB_USER=people
      - DB_PASS=S0l!dtyegre5sf5ygd5wgs
      - DB_DATABASE=bookstackapp
      - APP_URL=http://192.168.8.109:6875
    volumes:
      - /home/user/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=gvsrrgy5evtergdtur656345c
      - TZ=Asia/kolkata
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=people
      - MYSQL_PASSWORD=grge5r6e45w
    volumes:
      - /home/user/bookstack:/config
    restart: unless-stopped

**Comment by polarathene** [comment] 2021-05-05 08:27
> The DB_HOST parameter is used initially to update the .env file. Subsequent runs do not update the .env file, so have to do that manually.
> The .env only supports the internal bridged ip address (e.g. 172.xxx.xxx). Unfortunatley these addresses are behind the docker dhcp/dns which can change frequently. It DID NOT work to put the container name in place of the IP.

Thanks for mentioning this, helped restore bookstack that broke. For anyone else wanting the location of the `.env` file, it is located at `www` sub-directory of the volume you mount for `/config`.

---

I have not had any problems with the ENV vars since originally setting up of the container in 2019-2020. Recently the server host itself had a crash (ran out of disk space), and it seems at some point this created an overwritten `.env` file that was empty/blank.

Starting the container again gave a similar error shared here with the `forge` user and stating no password was used and permission errors (connection was successful):

```
Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'forge'@'bookstack.docker_default' (using password: NO) (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')

Exception trace:

1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'forge'@'bookstack.data_default' (using password: NO)")
     /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

2   PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'forge'@'bookstack.data_default' (using password: NO)")
     /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
```

`/docker/docker-compose.yml` example (generates default network based on directory name, thus `docker_default` like above example error snippet:

```
bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=hunter2
      - DB_DATABASE=bookstackapp
      - APP_URL=https://wiki.example.com
    volumes:
      - /path/to/data/app:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=hunter2
      - TZ=ETC/UTC
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=hunter2
    volumes:
      - /path/to/data/db:/config
    restart: unless-stopped
```

Setting the bookstack internal env vars probably would have been a viable workaround, but the existing empty `.env` was the cause that broke our wiki setup.

I know some users are citing that this `.env` file was storing a docker DNS internal IP, but this does not seem to be the case when viewing my `.env` file, it will use the same as `DB_HOST` and this works fine for resolving the IP even if the containers change IP.

It shouldn't make any difference but nginx-proxy is used for exposing the bookstack instance to the internet. But I am also used to the service typically taking a few minutes to be reachable with nginx bad gateway errors.

**Comment by homerr** [comment] 2021-07-30 19:03
I'm going to close this one off as we have a myriad of different issues in here, some of which I think have been fixed with other PR's where issues in the `sed` commands have been identified and resolved. Should any of your issues still be present please open new issues with all of the required info so we can re-look into it with up to date versions.

**Closed by homerr** 2021-07-30 19:03 UTC

**Comment by thetravellor** [comment] 2022-01-19 10:49
This docker is completely borked, DO NOT BOTHER WITH IT. Debugging from inital install? Yeah nah.
